package io.bosonnetwork.messaging;

import java.net.URI;
import java.net.URISyntaxException;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.bosonnetwork.CryptoContext;
import io.bosonnetwork.Id;
import io.bosonnetwork.Identity;
import io.bosonnetwork.utils.Base58;
import io.bosonnetwork.utils.ThreadLocals;
import io.netty.handler.codec.mqtt.MqttQoS;
import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.core.Promise;
import io.vertx.core.Vertx;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.net.PemTrustOptions;
import io.vertx.mqtt.MqttClient;
import io.vertx.mqtt.MqttClientOptions;
import io.vertx.mqtt.messages.MqttPublishMessage;
import io.vertx.mqtt.messages.MqttSubAckMessage;

class MessagingClientImpl extends AbstractVerticle implements MessagingClient {
	private static final String broadcast = "broadcast";

	private final Vertx instance;

	private final Identity user;
	private final Identity device;

	private final Id peerId;
	private final String host;
	private final int sslPort;
	private final int tcpPort;
	private final String sslCert;

	private final String clientId;

	private final CryptoContext cryptoContext;

	private final String inbox;
	private final String outbox;
	private final String privateInbox;
	private final String privateOutbox;

	private MessageListener listener;

	private int failures;
	private boolean disconnect;

	private MqttClientOptions mqttClientOptions;
	private URI mqttURI;
	private MqttClient mqttClient;
	private Promise<Void> connectPromise;
	private Map<Integer, Message> pendingMessages;

	private static final Logger log = LoggerFactory.getLogger(MessagingClientImpl.class);

	MessagingClientImpl(Vertx instance, Identity user, Identity device, Id peerId,
				String host, int tcpPort, int sslPort, String sslCert, MessageListener listener)
						throws MessagingException {
		this.instance = instance;

		this.user = user;
		this.device = device;

		this.peerId = peerId;
		this.host = host;
		this.tcpPort = tcpPort;
		this.sslPort = sslPort;
		this.sslCert = sslCert;

		this.listener = listener;

		this.clientId = getClientId(device.getId());

		inbox = "inbox/" + user.getId().toBase58String();
		outbox = "outbox/" + user.getId().toBase58String();
		privateInbox = "inbox/" + user.getId().toBase58String() + "/" + device.getId().toBase58String();
		privateOutbox = "outbox/" + user.getId().toBase58String() + "/" + device.getId().toBase58String();

		pendingMessages = new HashMap<>();

		this.cryptoContext = user.createCryptoContext(peerId);
		String password = getPassword(user, device);

		mqttClientOptions = new MqttClientOptions()
				.setAutoGeneratedClientId(false)
				.setClientId(clientId)
				.setUsername(user.getId().toBase58String())
				.setPassword(password)
				.setMaxMessageSize(16 * 1024)
				.setReceiveBufferSize(18 * 1024)
				.setKeepAliveInterval(60)
				.setHostnameVerificationAlgorithm("")
				.setCleanSession(false);
	}

	private static String getClientId(Id deviceId) {
		return Base58.encode(ThreadLocals.md5().digest(deviceId.bytes()));
	}

	private static String getPassword(Identity user, Identity device) {
		MessageDigest shasum = ThreadLocals.sha256();
		shasum.reset();
		shasum.update(user.getId().bytes());
		shasum.update(device.getId().bytes());
		byte[] digest = shasum.digest();
		byte[] sig = device.sign(digest);
		return Base58.encode(sig);
	}

	private Future<Void> attemptConnect(List<URI> uris, int index) {
		if (disconnect)
			Future.failedFuture("Stopped");

		if (index >= uris.size())
            return Future.failedFuture("No more candidate URIs to attempt");

		Promise<Void> promise = Promise.promise();

		URI uri = uris.get(index);

		log.info("Trying to connect to the messaging server {} @ {}", peerId, uri);

		if (uri.getScheme().toLowerCase().equals("ssl")) {
			mqttClientOptions.setSsl(true);
			if (sslCert != null) {
				mqttClientOptions.setTrustOptions(new PemTrustOptions().addCertValue(Buffer.buffer(sslCert)));
				mqttClientOptions.setTrustAll(false);
			} else {
				mqttClientOptions.setTrustAll(true);
			}
		} else {
			mqttClientOptions.setSsl(false);
		}

		MqttClient client = MqttClient.create(vertx, mqttClientOptions);

		client.closeHandler((v) -> onClose())
			.subscribeCompletionHandler(this::onSubscribeCompletion)
			.publishHandler(this::onMqttMessage)
			.publishCompletionHandler(this::onPublishCompletion)
			.publishCompletionExpirationHandler(this::onPublishCompletionExpiration)
			.publishCompletionUnknownPacketIdHandler(this::onPublishCompletionUnknownPacketId)
			.unsubscribeCompletionHandler(this::onUnsubscribeCompletion)
			.exceptionHandler((e) -> log.error("Messaging client error.", e));

		client.connect(uri.getPort(), uri.getHost())
			.onSuccess((ack) -> {
				log.info("Connected to the messaging server {} @ {}", peerId, uri);
				this.mqttURI = uri;
				this.mqttClient = client;
				promise.complete(null);
			}).onFailure((e) -> {
				log.warn("Failed to connect to the messaging server {} @ {}", peerId, uri);
				attemptConnect(uris, index + 1).onComplete(promise);
			});

		return promise.future();
	}

	private MqttClient getMqttClient() {
		return mqttClient;
	}

	@Override
	public Id getUserId() {
		return user.getId();
	}

	@Override
	public Id getDeviceId() {
		return device.getId();
	}

	@Override
	public boolean isConnected() {
		return mqttClient != null && mqttClient.isConnected();
	}

	private void onClose() {
		if (disconnect) {
			onDisonnected();
			log.info("Disconnected");
			return;
		} else {
			log.warn("Connection lost, will try to reconnect in the next few seconds");

			this.failures++;
			int delay = getRetryInterval();
			vertx.setTimer(delay, (tid) -> reconnect());
		}
	}

	private void onSubscribeCompletion(MqttSubAckMessage m) {
		List<Integer> grantedQoSLevels = m.grantedQoSLevels();
		log.info("Subscription complete:\n\t{} - {}\n\t{} - {}\n\t{} - {}\n\t{} - {}",
				inbox, grantedQoSLevels.get(0),
				privateInbox, grantedQoSLevels.get(1),
				outbox, grantedQoSLevels.get(2),
				broadcast, grantedQoSLevels.get(3));

		if (connectPromise != null) {
			log.info("Subscribe topics success");
			onConnected();
			connectPromise.complete(null);
		}
	}

	private void onUnsubscribeCompletion(int packetId) {
		// TODO:
	}

	private void onPublishCompletion(int packetId) {
		Message message = pendingMessages.remove(packetId);
		if (message == null) {
			log.error("INTERNAL ERROR: no message associated with packet {}", packetId);
			return;
		}

		CompletableFuture<Void> future = message.detachFuture();
		future.complete(null);
	}

	private void onPublishCompletionExpiration(int packetId) {
		Message message = pendingMessages.remove(packetId);
		if (message == null) {
			log.error("INTERNAL ERROR: no message associated with packet {}", packetId);
			return;
		}

		CompletableFuture<Void> future = message.detachFuture();
		future.completeExceptionally(new TimeoutException("Get message ACK timeout"));
	}

	private void onPublishCompletionUnknownPacketId(int packetId) {
		log.warn("INTERNAL WARN: unknown packet {}", packetId);
		Message message = pendingMessages.remove(packetId);
		if (message != null) {
			CompletableFuture<Void> future = message.detachFuture();
			future.complete(null);
		}
	}

	private void onMqttMessage(MqttPublishMessage mm) {
		String topic = mm.topicName();
		log.info("Got message at topic: {}", topic);

		try {
			byte[] payload = cryptoContext.decrypt(mm.payload().getBytes());
			Message message = Message.parse(payload);

			if (topic.equals(inbox))
				onMessage(message);
			else if (topic.equals(privateInbox))
				System.out.println("TODO");
			else if (topic.equals(outbox))
				onSent(message);
			else if (topic.equals(broadcast))
				onBroadcase(message);
		} catch (Exception e) {
			log.error("Failed to process the MQTT message", e);
		}
	}

	private void onConnecting() {
		if (listener != null)
			listener.connecting();
	}

	private void onConnected() {
		if (listener != null)
			listener.connected();
	}

	private void onDisonnected() {
		if (listener != null)
			listener.disconnected();
	}

	private void onMessage(Message message) {
		if (listener != null)
			listener.message(message);
	}

	private void onSent(Message message) {
		if (listener != null)
			listener.sent(message);
	}

	private void onBroadcase(Message message) {
		if (listener != null)
			listener.broadcast(message);
	}

	private List<URI> getMqttURIs() {
		List<URI> uris = new ArrayList<>(2);

		try {
			if (sslPort > 0)
				uris.add(new URI("ssl", null, host, sslPort, null, null, null));

			if (tcpPort > 0)
				uris.add(new URI("tcp", null, host, tcpPort, null, null, null));
		} catch (URISyntaxException e) {
			throw new IllegalStateException("Create MQTT URIs", e);
		}

		return uris;
	}


	private Future<Void> doConnect() {
		if (mqttClient != null && mqttClient.isConnected())
			return Future.succeededFuture();

		log.info("Connecting ...");

		disconnect = false;
		onConnecting();

		Map<String, Integer> topics = Map.of(inbox, MqttQoS.AT_LEAST_ONCE.value(),
				privateInbox, MqttQoS.AT_LEAST_ONCE.value(),
				outbox, MqttQoS.AT_LEAST_ONCE.value(),
				broadcast, MqttQoS.AT_LEAST_ONCE.value());

		List<URI> uris = getMqttURIs();


		connectPromise = Promise.promise();
		attemptConnect(uris, 0)
			.compose((v) -> getMqttClient().subscribe(topics))
			.onSuccess((v) -> {
				log.info("Subscribing the messages...");
			})
			.onFailure((e) -> {
				log.error("Failed to connect to the messaging service", e);
				onDisonnected();
				connectPromise.fail(e);
			});

		return connectPromise.future();
	}

	private int getRetryInterval() {
		if (failures == 0)
			return 0;				// no delay
		else if (failures <= 6)
			return (1 << failures);	// 2 ~ 64 seconds retry interval
		else if (failures <= 20)
			return 300;				// 5 minutes retry interval
		else
			return 600;				// 10 minutes retry interval
	}

	private Future<Void> reconnect() {
		if (disconnect)
			Future.failedFuture("Stopped");

		log.info("Connecting ...");

		return mqttClient.connect(mqttURI.getPort(), mqttURI.getHost())
			.andThen((ar) -> {
				if (ar.succeeded())
					log.info("Connected to the messaging server {} @ {}", peerId, mqttURI);
				else {
					log.warn("Failed to connect to the messaging server {} @ {}", peerId, mqttURI);

					this.failures++;
					int delay = getRetryInterval();
					vertx.setTimer(delay, (tid) -> reconnect());
				}
			}).map(null);
	}


	private Future<Void> doDisconnect() {
		if (mqttClient == null || !mqttClient.isConnected())
			return Future.succeededFuture();

		disconnect = true;

		return mqttClient.disconnect();
	}

	@Override
	public CompletableFuture<Void> connect() {
		CompletableFuture<Void> future = new CompletableFuture<>();

		vertx.runOnContext((v) -> {
			doConnect()
				.onSuccess(na -> future.complete(null))
				.onFailure(e -> future.completeExceptionally(e));
		});

		return future;
	}

	@Override
	public CompletableFuture<Void> disconnect() {
		CompletableFuture<Void> future = new CompletableFuture<>();

		vertx.runOnContext((v) -> {
			doDisconnect()
				.onSuccess(na -> future.complete(null))
				.onFailure(e -> future.completeExceptionally(e));
		});

		return future;
	}

	@Override
	public CompletableFuture<Void> sendMessage(Message message) {
		var future = new CompletableFuture<Void>();

		vertx.runOnContext((v) -> {
			byte[] payload = cryptoContext.encrypt(message.serialize());

			mqttClient.publish(outbox, Buffer.buffer(payload), MqttQoS.AT_LEAST_ONCE, false, false)
				.onSuccess(packetId -> {
					log.info("Sent message to {}", message.getTo());
					message.setPacketId(packetId);
					message.attachFuture(future);
					pendingMessages.put(packetId, message);
				}).onFailure(e -> {
					log.error("Sent message failed", e);
					future.completeExceptionally(e);
				});
		});

		return future;
	}

	@Override
	public CompletableFuture<Void> close() {
		return vertx.undeploy(this.deploymentID()).toCompletionStage().toCompletableFuture();
	}
}
