/*
 * Copyright (c) 2023 -      bosonnetwork.io
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package io.bosonnetwork.photonmessaging;

import java.util.Map;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import io.bosonnetwork.Id;

/**
 * Represents a message in the Photon messaging.
 */
public interface Message {
	/**
	 * Defines the types of messages supported by the service.
	 */
	enum Type {
		/** Standard user-to-user content. */
		CONTENT_MESSAGE,
		/** Internal RPC call or control instructions. */
		CONTROL_MESSAGE,
		/** User/Device status updates. */
		STATE_MESSAGE;

		@JsonValue
		public int value() {
			return ordinal();
		}

		@JsonCreator
		public static Type valueOf(int value) {
			return switch (value) {
				case 0 -> CONTENT_MESSAGE;
				case 1 -> CONTROL_MESSAGE;
				case 2 -> STATE_MESSAGE;
				default -> throw new IllegalArgumentException("Invalid message type: " + value);
			};
		}
	}

	/**
	 * Represents the content of a message, providing access to its metadata and body.
	 */
	interface Content {
		/**
		 * Retrieves the metadata headers associated with the content.
		 *
		 * @return a map where the keys are header names and the values are the corresponding header values.
		 */
		Map<String, Object> getHeaders();

		/**
		 * Retrieves the content type of the message.
		 *
		 * @return the content type as a string, representing the media type (e.g., "text/plain", "application/json").
		 */
		String getContentType();

		/**
		 * Retrieves the content disposition of the message.
		 *
		 * @return the content disposition as a string, indicating how the content is expected
		 *         to be displayed (e.g., "inline" or "attachment").
		 */
		String getContentDisposition();

		/**
		 * Retrieves the length of the content in bytes.
		 *
		 * @return the size of the content as an integer, or -1 if the length is unknown.
		 */
		int getContentLength();

		/**
		 * Retrieves the body of the content.
		 *
		 * @param <T> the expected type of the body
		 * @return the body of the content, cast to the specified type
		 */
		<T> T getBody();
	}

	/**
	 * Retrieves the unique identifier of this message.
	 * This ID is generated by the messaging repository and is unique within the current client instance.
	 *
	 * @return the message ID
	 */
	long getId();

	/**
	 * Retrieves the identifier of the conversation this message belongs to.
	 *
	 * @return the conversation ID
	 */
	Id getConversationId();

	/**
	 * Retrieves the identifier of the message recipient.
	 *
	 * @return the recipient's Id
	 */
	Id getRecipient();

	/**
	 * Retrieves the type of this message.
	 *
	 * @return the message Type
	 */
	Type getType();

	/**
	 * Retrieves the identifier of the sender.
	 *
	 * @return the sender's Id
	 */
	Id getFrom();

	/**
	 * Retrieves the serial number used for message sequencing and tracking.
	 *
	 * @return the serial number
	 */
	int getSerialNumber();

	/**
	 * Retrieves the timestamp when the sender created the message.
	 *
	 * @return the creation timestamp in milliseconds
	 */
	long getCreatedAt();

	/**
	 * Retrieves the timestamp when the message was received by the service or local client.
	 *
	 * @return the reception timestamp in milliseconds
	 */
	long getReceivedAt();

	/**
	 * Retrieves the raw payload of the message.
	 *
	 * @param <T> the expected type of the payload
	 * @return the payload object cast to the specified type
	 */
	<T> T getPayloadAs();

	/**
	 * Retrieves the payload wrapped in a {@link Content} object.
	 *
	 * @return the content representation of the payload
	 */
	Content getPayloadAsContent();
}